language: c++
os: linux
sudo: false

addons:
  apt:
    packages:
      - clang-3.9
      - libclang-3.9-dev
      - llvm-3.9-tools
      - python-pip
    sources:
      - llvm-toolchain-precise-3.9
      - ubuntu-toolchain-r-test

before_script:
  - mkdir build
  - cd build

script:
  - cmake -DCMAKE_CXX_COMPILER=clang++-3.9 -DCPACK_GENERATOR="TGZ;DEB" -DLIT_MODULE="/usr/lib/llvm-3.9/build/utils/lit/lit.py" ..
  - make all
  - make check
  - mkdir target_dir
  - DESTDIR=target_dir make install
  - make package

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6788df84412f2d288bb3
    on_success: change
    on_failure: always
    on_start: never
